### ISSUE TITLE
Core scale/log/metrics features

### ISSUE THREAD

**Issue by aleksandargosevski** [adonisjs/discussion#10]
1. Clustering (vertical scale) so the app can have multiple workers per machine.
2. Exposed `logger` so we can use it everywhere (should send to Syslog in the background).
3. Metrics via `statsd` so we can track things in graphite/graphana, etc.

**Comment by thetutlage** [comment]
Added logger provider, built on top of Winston. Docs here http://dev.adonisjs.com/docs/4.0/logger
