### ISSUE TITLE
[4.0] Bootstraper

### ISSUE THREAD

**Issue by RomainLanz** [adonisjs/discussion#14]
Hey everyone!

Currently the framework is booted by using the file `bootstrap/http.js` and `bootstrap/kernel.js`. Those files are hardcoded in the `adonis-app` repository and are difficult to update.

It may be more productive to create another package called `adonis-bootstraper` that will contain these files.

If we do that we will be able to easily update them without asking the developper to modify them by himself.

**Comment by rtablada** [comment]
I think there may need to be discussion around what is included in the `adonis-bootstrap` package vs what is left to these files.

From experience trying to boot up an app for testing, things that can be improved in these files:

1. Registering providers and aliases
2. Loading ENV
3. Starting the HTTP Server (and more importantly knowing when it has connected [but that is for a different RFC])

However there are customizations that should be left generated and easily customizable:

1. Loading Events
2. Loading Routes
3. Loading Kernel
4. Loading DB Factories

---

Coming from a Rails/Ember background however it would be nice to see something like:

```js
const Bootstrap = require('adonis-bootstrap')

module.exports = new Bootstrap()
```

Then maybe for customization you could do something like:

```js
const Bootstrap = require('adonis-bootstrap')

class MyBootstrap extends Bootstrap {
  boot() {
    use(Helpers.makeNameSpace('MyHttp', 'kernel'))
  } 
}

module.exports = new MyBootstrap
```

**Comment by RomainLanz** [comment]
Yup, I also like the way Aurelia does it.

```javascript
export function configure(aurelia: Aurelia) {
  aurelia.use
    .standardConfiguration()
    .feature('common/resources');

  if (environment.debug) {
    aurelia.use.developmentLogging();
  }

  if (environment.testing) {
    aurelia.use.plugin('aurelia-testing');
  }

  aurelia.start().then(() => aurelia.setRoot());
}
```

**Comment by RomainLanz** [comment]
More information about this: https://github.com/adonisjs/discussion/issues/19

**Comment by RomainLanz** [comment]
Closing since https://github.com/adonisjs/adonis-ignitor has been released.
