### ISSUE TITLE
Accessing Pivot Table's Fields In Many-To-Many Relationships

### ISSUE THREAD

**Issue by mertindervish** [adonisjs/discussion#2]
Hi. I'm working with Adonis for a while. I really appreciate your work 😄. Last week I end up making a many-to-many relationship like in the image below.

![Many-To-Many Relationship](http://i.imgur.com/8fwiSbt.jpg)

Lucid allows me to easily add value to pivot table's fields while attaching record (in my case I'm populating familiarity field in portfolio_skill table). But after the relationship is created I can't update it. The only way I found is by using Query builder.

Also when fetching portfolio's skills I need the familiarity field too. I achieved this by creating custom method in Skill Model which fetches familiarity field by using Query builder and attaches it.

Is there a more Adonis™ way of doing these? It will be an honor for me to develop these features (updateExistingPivot and withPivot methods) if they are not yet.

**Comment by thetutlage** [comment]
Closing since it is a repo related issue.
