### ISSUE TITLE
Lucid datetime formatting and timezone considerations

### ISSUE THREAD

**Issue by tremendus** [adonisjs/discussion#20]
The approach to AdonisJS is to create "developer joy" - and it does in almost every area :) 

... but I find a disproportionate amount of development time creating boilerplate code to manage dates and times. SQL is better stored as a datetime, but users/clients have regional (or even other preferences) for 'friendly formatting'. Simply mapping inbound model fields to sql-preferred format - perhaps best done by beforeCreate and beforeUpdate hooks - is fine, but reading them back to display for the client in views -including editable forms- seems to be best approached as getters. 

And the formatting is only one issue - timezones are another important part of any connected application. 

Propose a better, more lean, way of handling this issue

The following considerations and use cases apply. Please add other ideas, concerns. 

### saving/storage
- sql may be stored per migrations/knex datetime or other, as develop specified
- beforeCreate and beforeUpdate are required to be manually called on each field on each model, creates a lot of extra boilerplate which might be avoided

### reading/displaying
- client may have any other - even non-standard - format
- this can be mitigated by using moment under the hood as Adonis does now
- may not rely on view filters, as often times adonis may be used a API server without views
- currently requires getters on every field of every model, as there is no afterFind() hook, like other methods (other discussion item for this)

### ideas to improve
- assume date field uses names as /_at$/ (convention-over-configuration)
- option to include array of non standard date field names to also be included
- inversely, option to omit fields matching /_at$/ which are not date fields
- option to specify inbound (storage) date format globally, not just applying to created_at/updated_at as per current implementation
- option to specify outbound (api/view) date format globally (eg MM/DD/YYYY HH:mm:ss)
- consider timezone of inbound date format, based on datetime from client, which should include timezone, and map to inbound timezone (server defined, or Zulu default)

Keen to hear other ideas

**Comment by bitkidd** [comment]
Maybe I'm wrong and didn't get the whole problem, but I feel like `adonis-antl` can help you, there is a [formatDate](http://adonisjs.com/docs/3.2/internationalization#_formatdate_value_options) method, that can change date format depending on locale. So basically you just have to implement locales in your app, you save one for each user in database, or just read it from cookies.
In that case you keep datetime in DB in one single format, and change it in views for each single client.

**Comment by thetutlage** [comment]
I have re-imagined the way dates should be managed. Read this blog post https://adonisjs.svbtle.com/curious-case-of-date-formats-in-data-models
