### ISSUE TITLE
Consider additional hooks for Lucid ORM

### ISSUE THREAD

**Issue by tremendus** [adonisjs/discussion#21]
The new hooks in Lucid are great, but seems would be more useful with some additional hooks available from other ORMs like Sequelize or as I'm familiar with CakePHP ORM: 

From [Sequelize Docs]:(http://docs.sequelizejs.com/en/latest/docs/hooks/#order-of-operations)
```
1)
  beforeBulkCreate(instances, options, fn)
  beforeBulkDestroy(options, fn)
  beforeBulkUpdate(options, fn)
(2)
  beforeValidate(instance, options, fn)
(-)
  validate
(3)
  afterValidate(instance, options, fn)
  - or -
  validationFailed(instance, options, error, fn)
(4)
  beforeCreate(instance, options, fn)
  beforeDestroy(instance, options, fn)
  beforeUpdate(instance, options, fn)
  beforeSave(instance, options, fn)
  beforeUpsert(values, options, fn)
(-)
  create
  destroy
  update
(5)
  afterCreate(instance, options, fn)
  afterDestroy(instance, options, fn)
  afterUpdate(instance, options, fn)
  afterSave(instance, options, fn)
  afterUpsert(created, options, fn)
(6)
  afterBulkCreate(instances, options, fn)
  afterBulkDestroy(options, fn)
  afterBulkUpdate(options, fn)
```

Certainly, afterCreate, afterDestroy can be used to fire events eg to update a separate index of records (eg for application wide fast searching). 

And, beforeCreate is useful, for example to add a filter for customer_id or user_id to ensure that it applies to every query on a model, to support privacy or in multi-tenant applications. 

Would like to propose the addition of additional hooks for greater convenience, less code, and 'more joy' :)

**Comment by thetutlage** [comment]
Here's the list of all the hooks. http://dev.adonisjs.com/docs/4.0/database-hooks#_lifecycle_events

There are no `bulk` hooks, since Lucid has no bulk operations

**Comment by thetutlage** [comment]
Closing since no response from the issue reporter
