### ISSUE TITLE
sticky session

### ISSUE THREAD

**Issue by ihsanberahim** [adonisjs/discussion#23]
I know that adonisjs can use [redis](https://adonisjs.com/docs/3.2/sessions#_drivers) but i just looking for solutions to implement sticky session using AWS services and the [nodejs SDK](https://aws.amazon.com/sdk-for-node-js/)

- [elasticache](https://aws.amazon.com/elasticache/)
- [dynamodb](https://aws.amazon.com/dynamodb/)

Thank you.

**Comment by niallobrien** [comment]
@ihsanberahim Care to elaborate as to why exactly you require sticky-sessions? They're generally seen as a bad thing imo.

**Comment by ihsanberahim** [comment]
@niallobrien i newbie. This might be wrong. As far as i know. stick session required to implement loaf balancing because sessions are not stored in the application instance.

**Comment by niallobrien** [comment]
@ihsanberahim Only in the instance in which your architecture requires that the user always hits the same web server (among many) for every request. Generally speaking, if you utilise Redis for session storage, this no longer becomes an issue as all web servers can then retrieve your session information from a shared store.

**Comment by ihsanberahim** [comment]
If that so, we need to setup 2 instances for the application and the redis. I think there will be resources waste.

I would suggest to use cloud service like aws elasticache instead.

**Comment by niallobrien** [comment]
It's not a requirement, this is only a concern if you've grown beyond one web server. That is, only switch to using something like Redis for session storage when you need to. I don't see how resources are wasted.

**Comment by thetutlage** [comment]
Not coming, since it is not ideal to scale via sticky sessions and should better store sessions inside `redis` and Adonis does have a redis driver for sessions
