### ISSUE TITLE
Cannot seem to reverse paginate records!

### ISSUE THREAD

**Issue by manoj-manoharan-backup-old** [adonisjs/discussion#25]
I'm trying to paginate records in reverse order, from a order of recent to older records.

What's the efficient way?

**Comment by thetutlage** [comment]
Use `orderBy` http://adonisjs.com/docs/3.2/query-builder#_orderby_column_direction_asc

**Comment by thetutlage** [comment]
And please create issues on the dedicated repos, since this repo is for discussing the upcoming features.

**Comment by thetutlage** [comment]
This issue was moved to adonisjs/adonis-lucid#100
