### ISSUE TITLE
auth system

### ISSUE THREAD

**Issue by Epichris360** [adonisjs/discussion#27]
Hi. Im loving the framework exactly what i was looking for(coming from playing around with rails and laravel). How have you guys implemented user authentication? i've been thinking about building my own. But if there's a solution out there or a suggestion, I'd greatly appreciate learning about it.

Also has anyone tried to use passportJS with adonis?

**Comment by thetutlage** [comment]
Checkout the docs once http://adonisjs.com/docs/3.2/authentication

**Comment by Epichris360** [comment]
i decided to try and build my own from the docs after writing this, looking good so far. Really liking the framework.

**Comment by mphill** [comment]
Is there any documentation for http://adonisjs.com/docs/3.2/authentication#_extending_auth_provider in the 4.0 dev docs? 

Also is there a preferred method to store a global in-memory database so all have access to it?
