### ISSUE TITLE
Growing community needs?

### ISSUE THREAD

**Issue by Maxximus007** [adonisjs/discussion#3]
Just scratched the surface, but I'm impressed with the clean code and lack of boilerplate! 

I believe the community will grow rapidly, and it might be good to think about a forum? I know Rally is in the works, so perhaps getting it online would help supporting newbies (like me) and spreading the word, even if it's not yet finalised completely.

**Comment by atinux** [comment]
Would love to see [adonis-rally](https://github.com/adonisjs/adonis-rally) finished, it will be a great demonstration of the beauty of AdonisJS, simple code, powerful features.

**Comment by thetutlage** [comment]
Yeah waiting for some more time before I launch a forum. `adonis-rally` is a demo project showing how to build something simple with Adonis. 

Also I am going to build 2-3 more demo apps after completing the features pipeline. Glad you guys ❤️  the framework

**Comment by thetutlage** [comment]
Closing since we have forums now
