### ISSUE TITLE
"use" function

### ISSUE THREAD

**Issue by tonskey** [adonisjs/discussion#32]
Hello! Where declare "use" function?

**Comment by RomainLanz** [comment]
Hey @antonVl !

`use()` function is provided by the [IoC Container](http://adonisjs.com/docs/3.2/ioc-container) of AdonisJs ([adonis-fold](https://github.com/poppinss/adonis-fold)).

This function will try to resolve a binding or a namespace defined in your Adonis configuration file and will then fallback to the default `require()` function to import a package if it didn't find anything.

<hr>

* [what is the 'use' keyword in javascript?](https://stackoverflow.com/questions/41268452/what-is-the-use-keyword-in-javascript)

**Comment by tonskey** [comment]
thx @RomainLanz  for answer. I have a related question. Model in adonisjs declare with class. But, for example, in controllers, we connect our model with "use". So, "use" function return a pure class and we work with static method, or instance of model class?  
P.S Sorry for my bad English :)

**Comment by RomainLanz** [comment]
Yes.

`use()` return a class so you need to instantiate it if you want to use method inside. You can use `make()` if you want directly an instantiated class.

**Comment by thetutlage** [comment]
Closing and must be discussed on forum
