### ISSUE TITLE
Password reset and email verification

### ISSUE THREAD

**Issue by ianwalter** [adonisjs/discussion#35]
The auth system is nice but almost every system that uses it would also need a way to reset passwords (Forgot Password?) and, to a lesser extent, email verification. I would be happy to write a system for storing and verifying tokens to accomplish this functionality if it's not being done already. I'm guessing this should be it's own separate addon? I'm not sure what it should be called or if just adding it to the auth addon would be better. Thoughts?

**Comment by thetutlage** [comment]
Yup it makes sense to have it as a different add-on, so that people who want it can use it

**Comment by thetutlage** [comment]
Feel free to talk on forum about it, closing since not actionable

**Comment by Tinostarn** [comment]
Hey,

Had something been developed since or do I still need to implement user email validation manually ? 
Can't seem to find anything on the doc

**Comment by thetutlage** [comment]
Checkout https://github.com/adonisjs/adonis-persona

**Comment by Nainabbas** [comment]
adonis-persona is for adonis >=5.0.6 ??? anything else?

**Comment by RomainLanz** [comment]
What do you mean @Nainabbas?

**Comment by Nainabbas** [comment]
@RomainLanz  i mean i does not work on adonis 4.1 for me.

**Comment by RomainLanz** [comment]
It should work.

Adonis Persona has been created for Adonis 4.*
`@adonisjs/framework` version is independent from the "Adonis" Version.

**Comment by Agilulfo1820** [comment]
@RomainLanz  Can I use Persona only for its forgotPassword and verify the email feature and handle everything else by hand with JWT authentication?
