### ISSUE TITLE
Is there any plan to develop a micro-framework similar to Lumen?

### ISSUE THREAD

**Issue by JKChen** [adonisjs/discussion#36]
Adonis is awesome!
Is there any plan to develop a micro-framework similar to Lumen? Or add-on of adonis?

**Comment by webdevian** [comment]
Yes - See https://github.com/adonisjs/discussion/issues/8

**Comment by JKChen** [comment]
Thanks. That‘s cool~

**Comment by ajcastro** [comment]
Cool!

**Comment by thetutlage** [comment]
Use `--api-only` flag when creating a new app. It will create an application which is tailored for API servers.

```bash
adonis new yardstick --api-only
```
