### ISSUE TITLE
Promise support  on methods that requires callback

### ISSUE THREAD

**Issue by ajcastro** [adonisjs/discussion#37]
Is there a promise-approach for methods for example the `connect()` method (http://www.adonisjs.com/docs/3.2/websocket#_connect_callback) :
```javascript

const client = io.channel('chat')
client.connect().then(function () {
  // all good
}).catch(function () {
  // do something
});
```

**Comment by thetutlage** [comment]
AdonisJs supports async/await fully, which are in-turn promises
