### ISSUE TITLE
how to make a query builder with whereNested in adonisjs

### ISSUE THREAD

**Issue by dguzman1012** [adonisjs/discussion#4]
Hi everyone, how are you??? 

I'm coming here with a simple question: is there a way to use _whereNested_ functionality in Adonisjs just like Laravel does?

**Comment by thetutlage** [comment]
@dguzman1012 What do you want to achieve? I am not sure about how `whereNested` works in laravel

**Comment by dguzman1012** [comment]
Hi @thetutlage!! well... I use this method in Laravel to pass a _clousure_ into the Where method and procesing some data in order to build the final query.

Something like this: 

```php
$profiles = DB::table('profiles')->whereNested(function($query) use ($columns, $mysearch, $dist, $disctance_select){
    /* Building the query */
}```

**Comment by thetutlage** [comment]
You can do same using `where`.

```js
where(function () {
  this.where('id', 1).orWhere('id', '>', 10)
})
```

**Comment by dguzman1012** [comment]
@thetutlage Thank you!! Let me try this way...
