### ISSUE TITLE
Replace lodash wrapper with collect.js

### ISSUE THREAD

**Issue by hailwood** [adonisjs/discussion#40]
https://github.com/ecrmnn/collect.js

> Collect.js offers an (almost) identical API to Laravel Collections 5.4.

**Comment by thetutlage** [comment]
Actually in 4.0 I am removing collection with serialisers, which means you get an instance of a serialiser.

The beauty of serialiser is you can create or use different serialiser for each/all models and they are the one who structure the output of your model.

Thinks becomes helpful if you follow certain Json structure for your API's for example http://jsonapi.org is quite popular and you can have a serialiser for that

**Comment by hailwood** [comment]
@thetutlage sounds like there's a lot of cool changes coming with v4.0
I'm just playing at the moment rather than building anything for production so kinda tempted to start fiddling with the 4.0 setup anyway to help with bug testing etc. Any chance there's a repo somewhere I can base a project off?

**Comment by thetutlage** [comment]
4.0 dev release is out for a while and serializers are in place. So there is no need for any collection
