### ISSUE TITLE
Support UUID with binary(16)

### ISSUE THREAD

**Issue by shinaBR2** [adonisjs/discussion#42]
Hi all,
I have built an app with MySQL - Adonis - VueJS and in database, I have a `uuid` with `binary(16)` data type column in table `users`. Everything will be fine if I just use `VARCHAR` or `CHAR`. But, when I use jwt authenticator, it's failed to find user from jwt payload because the uuid should be convert to binary(16) like that
`uuid = Buffer.from(uuid, 'hex');`

In my way, I add 2 fields (`isTransform` and `transformPrimaryKey`) in `auth.js` like that
![image](https://user-images.githubusercontent.com/8222892/28448337-803591ba-6e01-11e7-8a3d-b19dd80cf0a8.png)

and I have add some lines in `C:\Users\LAP11403-local\Documents\Projects\SWallet\node_modules\adonis-auth\src\Schemes\Jwt\index.js` like this

![image](https://user-images.githubusercontent.com/8222892/28448341-90d4054c-6e01-11e7-8043-b1d1c8aa7041.png)

Everything will be fine. Should I pull a request for this support?

**Comment by thetutlage** [comment]
Yes, you can, `transformPrimaryKey` will be sufficient enough and there is no need for `isTransform`. Since we can check for `typeof (transformPrimaryKey) === 'function'`

**Comment by thetutlage** [comment]
Yes, you can, `transformPrimaryKey` will be sufficient enough and there is no need for `isTransform`. Since we can check for `typeof (transformPrimaryKey) === 'function'`

**Comment by thetutlage** [comment]
Closing since no response from the issue reporter and not actionable as well
