### ISSUE TITLE
Edge Template View plugin for Intellij Editor

### ISSUE THREAD

**Issue by rindia** [adonisjs/discussion#46]
Dear Developer,
I need a plugin/name for intellij editor for edge tempalte

Regards
Rohit Saini

**Comment by mtamadon** [comment]
Hi  @rindia ,
 I am using PHP storm (a product from intellij) & I am using 'laravel blade' plugin for developing edge templates , it may help you but we really need edge plugin for intellij/webstorm/phpstom because edge has lots of differences with blade. @thetutlage

**Comment by thetutlage** [comment]
I don't use PhpStorm or WebStorm. There are plugins for `Vscode`, `Atom` and `Sublime`. 

You can help creating, if you use those editors.

**Comment by rindia** [comment]
@thetutlage  as per my requirement, i hv to use only intellij editor for Adonis project.... plz help / provde edge plugin for Intellij..... 

Regards
Rohit Saini

**Comment by thetutlage** [comment]
I shared my views on same. Sorry atleast for now, I don't have bandwidth to create a plugin for intellij, but happy to help with guidance.

**Comment by juan-cortes** [comment]
If all you want is syntax highlighting, add `.edge` to the file types linked to `blade` in the preferences window. Syntax is similar enough, haven't run into any issues so far.

![image](https://user-images.githubusercontent.com/4631227/33404636-fae5109c-d59f-11e7-84c7-5543a7cfba65.png)

**Comment by mtamadon** [comment]
@juan-cortes : 
As I said I am using blade syntax highlighting but it has some problem with "@!" , @component  and also  It supports php syntax (ex. $ for var , $vars as var & ...) not JS!

**Comment by osplaza32** [comment]
hi i look for the same for webstorm!!!
regards

**Comment by betaWeb** [comment]
Hi,

A PHPStorm/IntelliJ/Webstorm plugin could be great :)

**Comment by l3est** [comment]
any news about webstorm .edge support?

**Comment by buuug7** [comment]
not new , a shit with webstorm

**Comment by RomainLanz** [comment]
Hey everyone,

The reply is still the same as the one from @thetutlage.

Creating a plugin to support Edge is complex and require a lot of time. Time that we haven't.
Feel free to [submit a ticket](https://intellij-support.jetbrains.com/hc/en-us/requests/new?ticket_form_id=66731) in there system or ask on their forum.
