### ISSUE TITLE
npm packages

### ISSUE THREAD

**Issue by mhingston** [adonisjs/discussion#47]
Is there a plan to have all adonis packages available under the scope [**@adonisjs**](https://www.npmjs.com/search?q=scope:adonisjs)? Some adonis packages have been published under this scope and others like [adonis-websocket](https://github.com/adonisjs/adonis-websocket) haven't.

**Comment by RomainLanz** [comment]
Hey ! 👋 

All Adonis 4.0 packages are published under @adonisjs. If some aren't that means they aren't adapted for 4.0 yet.

**Comment by mhingston** [comment]
@RomainLanz Thanks for the clarification, keep up the great work!
