### ISSUE TITLE
Dev enviroment setup?

### ISSUE THREAD

**Issue by gcigd** [adonisjs/discussion#48]
I've been trying to setup a dev environment. Is there any guide?

**Comment by RomainLanz** [comment]
Hey @K-Eo 👋 

What do you mean by a dev environment?
The only thing you need to have on your system is:

1. Node.js & npm installed
2. A text editor
3. A terminal

**Comment by gcigd** [comment]
I want to test a custom feature for adonis-framework in my app but I can figure out how to make it work.

@RomainLanz thanks for your fast answer.

**Comment by RomainLanz** [comment]
Ok I get it.

You can simply fork the `adonis-framework` repository, make your change and then install `adonis-framework` from your fork instead of the official package.

This will let you test the code you want to add to `adonis-framework` without breaking anything 👍

**Comment by gcigd** [comment]
@RomainLanz that is great. Thank you for your help and feel free to close this issue.
