### ISSUE TITLE
More service provider functionality

### ISSUE THREAD

**Issue by shanedaugherty** [adonisjs/discussion#54]
Hello,

It would be great to be able to add Routes, Models, Controllers, and Migrations through a service provider.

Perhaps this is already possible but I could not find anything in the documentation about it.

**Comment by thetutlage** [comment]
Yes it is 100% possible. If you look closely, `Controllers`, `Models` and almost everything is an IoC container namespace, it does not matter where the file for that namespace is, it can be inside your own project or inside a package. For example

```js
class MyController {
  profile () {
  }
}

ioc.bind('MyController', function () {
  return new MyController()
})
```

Inside your routes.

```js
Route.get('me', '@provider:MyController.profile')
```

**Comment by ghost** [comment]
I had a feeling that was the case. Thank you for taking the time to reply.
