### ISSUE TITLE
Possible bug with validation messages

### ISSUE THREAD

**Issue by charlcallpay** [adonisjs/discussion#55]
Hi guys, I think I might have found a bug with the Validator
If I have 2 rules that both fail on validation the messages function will only return the first one
Example:
if (validation.fails()) {
            return validation.messages();
        }

 Even if 2 rules fail will only return one error
[
{
   "field": "email",
   "validation": "email",
   "message": "email validation failed on email"
}
 ]

**Comment by RomainLanz** [comment]
Hey @charlcallpay! 👋 

Are you using `validate()` or `validateAll()`?

**Comment by charlcallpay** [comment]
Hi Romain using validate(), will try the other way

**Comment by RomainLanz** [comment]
Yes !

`validate()` will stop validating when it gets an error.
If you want to have all error you must use `validateAll()`.

**Comment by charlcallpay** [comment]
Thanks Romain works perfectly now
