### ISSUE TITLE
Namespace for 3rd party adonis providers

### ISSUE THREAD

**Issue by webdevian** [adonisjs/discussion#56]
As all official adonis v4 modules have moved to a new namespace on npm, should 3rd party modules follow suit? I don't think we can publish under the @adonisjs namespace directly, what should we do @thetutlage?

**Comment by thetutlage** [comment]
Publish them on npm under your account

**Comment by webdevian** [comment]
@thetutlage Is that better than just posting it to the global namespace on npm? 

`@webdevian/my-adonis-module` doesn't seem to be any better than `my-adonis-module` 

Should we use a naming convention? i.e `adonis-*` or `adonis-*-provider`?

**Comment by thetutlage** [comment]
Closing since not actionable
