### ISSUE TITLE
Add the shebang to ace (not sure where to add issues for Adonis 4 app)

### ISSUE THREAD

**Issue by mattcdavis1** [adonisjs/discussion#59]
Looking [here](https://github.com/adonisjs/adonis-app) i was unable to locate the 4.x branch for adonis-app.  Where should i go to create issues for adonis-app?  

The request i had was to add the shebang to ace which is not there currently after following the install instructions from adonisjs.com.  The reason for this request is [here](https://github.com/Microsoft/vscode/issues/40532#event-1395735864) (see response from weinand).  Also, looks like the shebang was in a [previous version of ace](https://github.com/adonisjs/adonis-app/blob/master/ace) as well.

**Comment by thetutlage** [comment]
The reason I removed `shebang` is that is works weirdly based upon the operating system you are on, especially Windows.

So my views are to keep it like any other `Javascript` file over a executable file.

**Comment by thetutlage** [comment]
Also regarding `adonis-app` repo. We have different boilerplates for couple of use cases.

1. [Fullstack app](https://github.com/adonisjs/adonis-fullstack-app)
2. [For REST API](https://github.com/adonisjs/adonis-api-app)
3. [Slimmest possible app](https://github.com/adonisjs/adonis-slim-app)

**Comment by mattcdavis1** [comment]
ok - makes sense. thanks!
