### ISSUE TITLE
Ideas / suggestions

### ISSUE THREAD

**Issue by ctf0** [adonisjs/discussion#6]
* ### If You Have An Idea Or A Suggestion To Improve Adonis, Please Leave A Comment And It Will be Added Into Here So EveryOne Can Review It.
.
.
.

---

* add the ability to change the field name
atm if you have a field with the name `password_confirmation`, when validating you would get `required validation failed on password_confirmation`,
while it would be better and more user friendly if we can change that to `Confirm Password`, something like **Specifying Custom Attributes In Language Files** https://laravel.com/docs/5.3/validation#custom-error-messages

---

* add an exception when the app cant connect to the DB 
http://adonisjs.com/docs/3.1/error-and-exceptions#_throwing_exceptions

---

* add `route namespace`

ex. app/Http/Controllers/Auth/SocialController
```js
Route.group('social', function () {

  Route.get('/:provider/login', 'SocialController.redirect')
  Route.get('/:provider/authenticated', 'SocialController.handleCallback')

  // etc...
}).namespace('Auth')
```

--- 

* use validation files instead of default `{{validation}} validation failed on {{field}}`
https://github.com/adonisjs/adonis-validation-provider/issues/8
https://github.com/ctf0/adonis-validation-messages

---

* display validation msg for specific input
https://github.com/adonisjs/adonis-validation-provider/issues/7

---

* `vendor:publish`
ex. installing the mail package require the user to download the config file, while each package should have all of its own files included and by using the cmnd the files gets moved to its correct path.

---

* use `yarn` if its found instead of `npm` for the cli

---

* add seeding option for migration
```bash
# before
ace migration:refresh
ace db:seed

# alias
ace migration:refresh --seed
```

---

* `ace cmnds`
maybe we can add a way so `ace` could add a separator automatically after each group of cmnds e ex.
![screen shot 2016-11-25 at 10 52 38 pm](https://cloud.githubusercontent.com/assets/7388088/20636942/296d7456-b380-11e6-93fb-bf6d4713dbfb.jpg)
i have made the implmentation already as a cmnd but sadly now the user have to add this cmnd after each group to get something like the above 😢 

---

* `routes.js`
maybe instead of bloating the file with a million route, we can instead create a `Routes` folder at the `root` and simply add a loop that automatically read all the routes from the files in that folder to the `routes.js`, same on how `db:seed` work 

---

* `this.addHook()`
so instead of solely relying on the `hook files` the user can also use `closure` for simple things as well, ex.
```js
const Hash = use('Hash')
static boot () {
  super.boot()
  this.addHook('beforeCreate', function * (next) {
    this.password = yield Hash.make(this.password);
    yield next
  })
}
```

---

* `Route.group()` https://github.com/adonisjs/adonis-framework/issues/379

---

* `toJSON()`
```js
// before
yield response.sendView('users', {users: users.toJSON()});
// alias
yield response.sendView('users', compact(users));
```
**EDIT**
currently its only needed when using `Lucid` but it would be better if user can write 
`yield response.sendView('users', {users: users});` and the `toJSON()` gets binded internally when needed

---

* `fill()`
```js
// before
const post = yield Post.findBy('id', 1)
post.fill({body: 'Adding some new content'})
yield post.save()
// alias
const post = yield Post.findBy('id', 1)
yield post.update({body: 'Adding some new content'})
```

---

* `ids()` 
imho its not needed and it could be removed as it give `array of items` rather than `array of objects` which would require a slightly different syntax `toJSON` when returning & rendering the data to view.

---

* `destroy(item)`
```js
// before
yield Database.table('users').where(primaryKey, item).delete();
// new
yield User.destroy(item);
```

---

* `gather(field/s)`
```js 
// before 
yield Database.table('users').select('email', 'username').orderBy(primaryKey);
// new
yield User.gather('email', 'username');
// result
[
{
  email: abc,
  username: foo
},
{
  email: xyz,
  username: bar
},
{
  // etc ...
}
]
```

---

* `last()`
```js 
// before
yield User.pickInverse(1);
// alias
yield User.last();
```

---

* `first()`
```js 
// before
yield User.pick(1);
// alias
yield User.first();
```

**Comment by thetutlage** [comment]
Okay let's discuss them one by one

1. `first()` and `last()` seems good to me.
2.  `gather` should be `pluck` something knex already has.
3.  `destroy` can be called directly via user model. `User.query().where('id', 1).delete()`
4.  `toJSON` works fine for JS world. `compact` is more of Php convention and will require to add a global. So no to this.
5. `this.addHook` already accepts closure.
6. You can create a routes directory and require all the files from that dir to `routes.js` file.
7. `ace cmnds`. Yes I want to improve the help screen.

**Comment by ctf0** [comment]
1- i tried `pluck` but didnt work, also according to docs http://adonisjs.com/docs/3.1/query-builder#_pluck_column it only works with one column, while `gather` works with both single or multi

2- `destroy` is more of a short alias for the original chain

3- u r correct that compact belong to the php world, but i was just after something that makes writing `{users: users.toJSON()}` shorter, which i've already tried to change in the core `sendView` function but didnt work :disappointed: 

4- `this.addHook` i believe we need to add the closure part to the docs then

5- `routes.js` i have done that but they need to be added manually, is there a way to make like a loop that require files automatically ? like https://ctf0.wordpress.com/2016/10/01/split-routes-into-categories-in-laravel/

6- `Route.group()` could be added as a new implementation in the next major release ex.v4 to avoid the breaking changes for current users

**Comment by thetutlage** [comment]
1. Will make `pluck` pick multiple fields too.
2 & 3. This is micro management and I don't think the syntax is verbose. You can implement your own methods if required.
4. Will add to docs
5. Use http://npmjs.org/package/require-all
6. Will look into possible options

**Comment by ctf0** [comment]
about the `toJson()` i tried
```js
const Response = use('Adonis/Src/Response')
Response.macro('view', function(view, data) {
  this.sendView(view, { data: data.toJSON() })
})

// and call it
const users = yield User.all();
yield res.view('users', users);
```
but i get error 
`You may only yield a function, promise, generator, array, or object, but the following object was passed: "undefined"` 
could u plz help me on how to implement it correctly ?

**Comment by thetutlage** [comment]
you have to return `this.sendView` from your macro

**Comment by ctf0** [comment]
now a new error `data.toJSON is not a function`

also btw `toJSON` is inconsistent or maybe am not exactly aware when do i need to use it vs not.
ex.
```js
// 1
const posts = yield User.all()
yield response.sendView('home', { users: users.toJSON() })

// 2
const users = yield Database.table('users').select('*');
yield response.sendView('users', { users: users });
```
while using `response.send(users)` give the same result. (array of objects)

so is it possible to have the `toJSON` done internally by adonis when its needed, so the user would use the same syntax no matter the method he/she use ?

**Comment by thetutlage** [comment]
You call `toJSON` on collections and only `Lucid` model returns collections, when you call `fetch` method.

Database provider returns plain arrays

**Comment by ctf0** [comment]
okay, is there a way to make DB calls return a collection as well ? if u dont feel like adding it to the core maybe a global call like the db debug http://adonisjs.com/docs/3.1/database-setup#_globally then ?

and any solution for the `data.toJSON is not a function` ?

**Comment by ctf0** [comment]
added 
1- `migration:refresh --seed`
2- use `yarn` instead of `npm`

**Comment by ctf0** [comment]
added `vendor:publish`

**Comment by ctf0** [comment]
added
1- route namespace
2- have an exception when the app cant connect to the DB
3- the ability to change the field name

**Comment by twilroad** [comment]
@ctf0 where is the code for route namespace?

**Comment by ctf0** [comment]
@twilroad  this is just a suggestion, its better u to check with @thetutlage

**Comment by twilroad** [comment]
@ctf0 you marked as added, so i think it was implemented.
