### ISSUE TITLE
Add stack/push/prepend to Edge

### ISSUE THREAD

**Issue by pedzed** [adonisjs/discussion#61]
It would be nice to have stacks, exactly like Laravel's Blade engine.

Related: https://laravel.com/docs/5.6/blade#stacks

![Edge stacks](https://user-images.githubusercontent.com/8146593/39089621-76fe6952-45cc-11e8-8ca2-300e281cf464.png)

**Comment by pedzed** [comment]
`prepend`ing is not too important for me personally, but being able to `push` to a `stack` is really essential. For example, on some pages I might need jQuery, but on other pages I'd rather not include them.

**Comment by thetutlage** [comment]
The concept of stacks itself is too complicated, you can simply use sections here.

### Master template

```
@section('scripts')
   <script src="1.js"></script>
   <script src="2.js"></script>
@endsection
```

Now let's say, you want one more script in a different template

```
@section('scripts')
   @super
    <script src="3.js"></script>
@endsection
```

`@super` will inherit from the master template and adds the 3rd one.
