### ISSUE TITLE
how can I create a fake data by combining a "custom data" with faker

### ISSUE THREAD

**Issue by malepatip** [adonisjs/discussion#63]
Hello,

I am looking for a way to create a fake JIRA/TFS issues, for which I wanted to use FAKER API, but not sure how can I generate a data in this scenario. My JIRA/TFS numbers look like these "JIRA-1234" or "TFS-54367"

Can someone help me with a reference example on how factory and seeders looks like?

**Comment by malepatip** [comment]
I was able to figure it out 'JIRA-'+ faker.natural({min: 500000, max: 699999})

**Comment by RomainLanz** [comment]
You can even use template literals.

```js
`JIRA-${faker.natural({ min: 500000, max: 699999 })}`
```
