### ISSUE TITLE
Re-thinking Forms/Validation

### ISSUE THREAD

**Issue by K3TH3R** [adonisjs/discussion#64]
First and foremost, thank you for Adonis. I've been working in frontends (and primarily for Django) for several years and Adonis has been such a pleasure to start my journey into learning/building my own backends. 

One thing I've been missing so far is the way that it handles forms within the view context. For example, on the frontend, almost all of my templates looking like a big mixture of lines like this:

```
{% include "shared/forms/text.html" with field=form.first_name %}
```

And that's for one field for the `form` object within the context. Then inside of that template it'll be something like this:
```
<div class="form-group">
  {% if field.label %}
    <label for="{{ field.id }}">{{ field.label }}</label>
  {% endif %}
  <input type="text" class="form-control" id="{{ field.id }}" name="{{ field.name }}" value="{{ field.value }}">
  {% if field.error %}
    <div class="alert alert-danger alert-field">
      {{ field.error }}
    </div>
  {% endif %}
  {% if field.helpText %}
    <small class="form-text text-muted">{{ field.helpText }}</small>
  {% endif %}
</div>
```

I've already figured out how to do something somewhat similar like this:
```
// view
@!component('components.forms.text', label='Zip/Postal Code', name='zip', error=getErrorFor('zip'), value=old('zip', ''))

// component
<div class="form-group">
  @if(label)
    <label for="id_{{ name }}">{{ label }}</label>
  @endif
  <input type="text" class="form-control{{ extraClasses }}" id="id_{{ name }}" name="{{ name }}" value="{{ value }}">
  @if(error)
    <div class="alert alert-danger alert-field">
      {{ error }}
    </div>
  @endif
  @if(helpText)
    <small class="form-text text-muted">{{ helpText }}</small>
  @endif
</div>
```

But in the case of many routes, forms, fields, custom validators, etc. this ends up being a lot of repetition across the project in many different areas. So my proposal is as such:

1. Have a custom form class similar to how you have Validators right now, something like this:
```
class SignupForm {
  return {
     action: '/signup', // it would really amazing to do `route('signup')` here
     method: 'post',
     fields: [
       'email': {
          type: 'email',
          label: 'E-Mail',
          help: 'E-mail must match the user@domain.com format',
          rules: 'required|email|unique:accounts',
          attrs: [ // key-value pairs that get rendered 1:1 in the field output
            required: true,
            placeholder: 'username@domain.com',
            classes: 'form-control'
          ],
          messages: {
            unique: 'That e-mail has already been used.'
          },
          sanitization: 'normalize_email|strip_tags'
       },
       // more fields
    ]
  }
}
```
In the case of this above example, the `required` and `email` rules would default to the Indicative rules, but it would use the `messages.unique` value.

2. Allow the ability to assign this form to a route context like you currently assign custom validators:
```Route.get('signup', 'AccountController.signup').form('Signup')```

3. And then within the view, you have a `{{ form }}` object that you can use in a few ways:
```
// view
<form action="{{ form.action }}" method="{{ form.method }}">
@each(field in form)
   @!component('components.forms.field',  field=field)
@endeach
</form>

// component
<div class="form-group">
  @if(field.label)
    <label for="id_{{ field.name }}">{{ field.label }}</label>
  @endif
  {{ renderField(field) }} // or maybe just {{ field }} ?
  @if(field.error)
    <div class="alert alert-danger alert-field">
      {{ field.error }}
    </div>
  @endif
  @if(field.helpText)
    <small class="form-text text-muted">{{ field.helpText }}</small>
  @endif
</div>
```

or:

```
// view
<div class="row">
   <div class="col-sm-6">
      @!component('components.forms.text',  field=form.email)
   </div>
   <div class="col-sm-6">
      @!component('components.forms.password',  field=form.password)
   </div>
</div>
```
The main thing here is that the frontend developer still has capacity to control/modify the field layout/rendering. 

4. In the case of large projects where the responsibilities between frontend and backend are split heavily, often the frontend knows little about the context of the view they're working on, so Django also provides a handy utility function that would be nice to have as well: `{{ form.as_p }}`. This basically loops through all the form fields and renders them out in between `<p></p>` tags.

[edit]
One other idea that would be interesting, albeit probably a lot of work and not entirely necessary, would be to allow some sort of inheritance/extraction of fields. For example, there's normally a few views you need password fields for (ie. signup, password reset after verification, change password). It might be nice on a route to do something like this: 
```
Route.get('change-password', 'AccountController.changePassword').form('Signup', ['password', 'confirm_password'])
// or if you want to be explicity
Route.get('change-password', 'AccountController.changePassword').formOnly('Signup', ['password', 'confirm_password'])
```
You're basically allowing them to specify only a subset for a form's fields.

**Comment by K3TH3R** [comment]
Actually, thinking about this a little bit more, it might make the most sense for this to be a method on the Model:
```
class Account extends Model {
   static get fields () {
     // "fields" schema from post above
   }
}
```
And then the forms are simplified by doing something more like this:
```
class SignupForm {
  return {
    method: 'post',
    action: '/signup',
    fields: Account.getFields(['email', 'password', 'password_confirm'])
  }
}
```
That `Account.getFields` line doesn't quite look write in relation to the model's method, but I think you get the idea.

**Comment by thetutlage** [comment]
There are couple of things in your original request. Let's start with one at a time.

## First
As applications are getting more user friendly and interactive. The one to one mapping of Models and Forms is getting smaller.

There are more than expected scenarios, where a single form may write to multiple database tables and hence interacting with multiple Models.

## Second
You are looking more of a form builder which can handle following for you: (correct me if I am wrong)

- Validations
- Automatic HTML markup
- Writing to database

I agree that this feature maybe desired by handful of people, but I again not every form is as simple as one to one mapping.

I suggest creating an RFC for same and if you are interested working on a separate package, which makes this possible for you and many others. I will be more than happy to help you and give feedback on same.

The RFC must have

- A clear problem you are trying to solve.
- The solution to the problem more as a concept than code.
- The implementation details for same.

If required, we can move this package to the core and you can be the lead maintainer of it.

**Comment by K3TH3R** [comment]
@thetutlage thank you for your thoughts and feedback. I agree that we're moving more and more away from one-to-one form/model relationships. However, I think for now, let's ignore the discussion about a "form builder" which isn't exactly what I'm thinking about. 

I think the problem I'm trying to solve is that, compared to most of the rest of the framework, the problem of accurately communicating input-related data between the frontend and backend of the application feels clunky and repetitive currently. For example, I've repeated "password" field information across multiple validators on the project I'm working on, and then I have to re-write aspects of that field information again within my templates.

What I'm suggesting is to allow the creation of model field schemas... essentially a centralized source of truth about the fields related to a model. This doesn't mean the validator uses every field related to a model, but instead of having to copy>paste lines between different validators if something changes, you update a central location and it would automatically propagate to any validators that make use of that field's schema. If implemented, this centralized field schema could then be used to also easily generate a form object that can be passed in the context (or alternatively returned through an API response). 

[edit]
Just stumbled on the RFC repo, so will fill one out in mid-September once I meet my deadline

**Comment by thetutlage** [comment]
Okay, I do get your intent. You are looking for a central place to manage fields, instead of repeating the same thing everywhere.
I believe, this central location can cover up a lot of stuff. Like `validations`, `markup` and so on.

To be frank, I don't have much idea on what's the best way to go with it. However, I am constantly brainstorming to make it possible and do see the value in
adding this feature

**Comment by K3TH3R** [comment]
Okay. I'll submit a proper RFC proposal in the RFCs repo with my initial ideas and we can start working through it with everyone else over there.
