### ISSUE TITLE
Webpage - Replacing gitub link from "community" with a more visible icon in the menu

### ISSUE THREAD

**Issue by cupofjoakim** [adonisjs/discussion#66]
When I recently discovered Adonis I was initially confused about whether or not the framework was open source, just because I couldn't see a github link on the homepage. Further investigation revealed the link under the "community" dropdown, but I feel that it could be more visible to drive more traffic here, which would bring contributors.

I would gladly make a PR, if the maintainers (I guess @thetutlage?) approves the suggestion. You might just want it as is as well, and I have full understanding for that :)

**Comment by RomainLanz** [comment]
Hey 👋 

I approve the suggestion, you can go ahead and make a PR in the https://github.com/adonisjs/adonisjs.com repository.

**Comment by cupofjoakim** [comment]
PR has been made, closing this.
