### ISSUE TITLE
Nested things (groups and resources)

### ISSUE THREAD

**Issue by lancedikson** [adonisjs/discussion#7]
It'd be convenient to have nested groups and resources. Maybe, they are quite different and shouldn't be at the same issue.
It was discussed in Gitter chat, so I' copy-paste it here: 

> Marko Bolliger @cannap Nov 28 13:29
> can i use Route.group in Route.group?
>
>Romain Lanz @RomainLanz Nov 28 13:29
> Not at this moment
> But this is in the roadmap
>
> Marko Bolliger @cannap Nov 28 13:30
> ok thx
>
> Harminder Virk @thetutlage Nov 28 13:37
> I don’t see any practical use case of nested Groups
>
> Dan Gamble @dan-gamble Nov 28 13:48
> My use case for it was creating an API group then inside that i had a group for users, articles, etc.
> 
>Romain Lanz @RomainLanz Nov 28 14:58
>I don’t see any practical use case of nested Groups
> @thetutlage To apply middleware
>
> Harminder Virk @thetutlage Nov 28 15:00
> You can simple apply them on each group and to keep it dry
> const list = [‘foo’, ‘bar’, ‘baz’]
> and then
> Route.group(1).middleware(list)
> Route.group(2).middleware(list)
> The nested syntax is gross and will create confusing in big projects on what the heck is really happening and in what order by middleware will be applied if I have middleware on parent and child group both
>
>Romain Lanz @RomainLanz Nov 28 15:01
> parent then child
>
> Harminder Virk @thetutlage Nov 28 15:02
> Yeah but then someone will come and say, child > parent. So it’s better to keep it plain
> 
> Romain Lanz @RomainLanz Nov 28 15:04
> If this "guy" come you can only say, "No, it's done by this way and it's logic".
> But to give you a real example case. Think about API routes. All API routes should be prefixed with /api/ but only some of them should use the auth middleware. So yes I can creating multiple group or I can create a group of routes to prefix /api and then create two groups inside. Both are valid and works
>
> Harminder Virk @thetutlage Nov 28 15:05
> It’s one or the other and I do not see any real win with nested groups, just you save couple of lines of code with good amount of confusion
> And things like these leads to micro management

I agree with @RomainLanz and have run into the problem when wanted to have something like that:
```javascript
/* prefixing group */
Route.group('version1', function () {
  /* authenticated group */
  Route.group('authenticated', function () {
    Route.resource('products', 'Api/V1/ProductsController');
  }).middleware('auth');
  
  Route.resource('articles', 'Api/V1/ArticlesController');
}).prefix('/api/v1');
```

And of course, nested resources could be very powerful thing. Example from Ruby world: http://guides.rubyonrails.org/routing.html#nested-resources

**Comment by RomainLanz** [comment]
What @thetutlage was saying is that we can create two group and "duplicate" the prefix.
This is easier to read and to maintain.

```javascript
Route.group(function () {
  Route.resource('articles', 'Api/V1/ArticlesController')
}).prefix('api/v1')

Route.group(function () {
    Route.resource('products', 'Api/V1/ProductsController')
}).middleware('auth').prefix('api/v1')
```

The only thing that need to be added is to be able to create route's groups without naming it.

**Comment by thetutlage** [comment]
Nested resources are already in place with `(dot)` notation. For example

```javascript
Route.resource('post.comments', 'CommentsController')
```

Problem with nested groups is that people will take them too far to a point where it will be hard to know which property have been set by which group. For example.

```javascript
Route.group('version1', function () {
  /* authenticated group */
  Route.group('authenticated', function () {

    Route.resource('products', 'Api/V1/ProductsController');

    Route.group('adminonly', function () {
      Route.resource('settings', 'Api/V1/SettingsController');
    }).middleware('auth:admin'); // some custom middleware to check for admins

  }).middleware('auth');
  
  Route.resource('articles', 'Api/V1/ArticlesController');
}).prefix('/api/v1');
```

What should happen in this case. Should `auth:admin` and `admin` middleware get merged, or nested group middleware should override the previous middleware.

Some will say it should concat but some will say my middleware are conflicting and they should override each other.

Here is an alternative way of doing it

```javascript
const apiPrefix = '/api/v1'

Route.resource(`${apiPrefix}/articles`, 'Api/V1/ArticlesController');
Route.resource(`${apiPrefix}/products`, 'Api/V1/ProductsController').middleware('auth');
Route.resource(`${apiPrefix}/settings`, 'Api/V1/SettingsController').middleware('auth:admin');
```

The routes file should be scannable in first look over a complex nested hierarchy, which needs a lot of calculation to understand which properties get merged in which sequence.

`groups` / `resources` are all about keeping the code DRY and when they get in your way, the option is to leave them and write the simplest code.

**Comment by thetutlage** [comment]
Group without name works for me and will be introduced in major release so that I can have luxury for breaking changes

**Comment by lancedikson** [comment]
> What should happen in this case?

I think, it should be merged, of course, because of the scopes. Group looks like a scope that describes what to do for those routes in it. But yeah, it makes sense to keep declaration flatter now. I think it mostly because of current using of `.prefix` and `.middleware`. It'd be clearer if those bindings go before declaration of routes like: 
```js
Route.group('v1', { prefix: '/api/v1' }, () => {
  Route.group('authenticated', { middleware: 'auth' }, () => {
    Route.resource('products', 'Api/V1/ProductsController');
    Route.resource('settings', 'Api/V1/SettingsController').middleware('auth:admin'); // here it goes through auth and then auth:admin because of the scope
  });
  
  Route.resource('articles', 'Api/V1/ArticlesController');
});
```
It looks quite clear and understandable, doesn't?
And then if you need more `auth:admin` you need to create a new group like that you've mentioned above.

**Comment by lancedikson** [comment]
Sorry for the nested resources — I hadn't seen that in the docs. Looks like they are missing there.

**Comment by thetutlage** [comment]
Added groups without names in 4.0
