### ISSUE TITLE
Light version / Lumen like

### ISSUE THREAD

**Issue by atinux** [adonisjs/discussion#8]
Hi!

Thanks for making for making adonis-framework, I love it.

Is there any way to have a light version of Adonis framework like Lumen for Laravel?
Making the views optional for example?

I would love to use Nuxt.js with Adonis and use Adonis for the API / Database.

What do you think?

**Comment by thetutlage** [comment]
Yup nuxt and next both are great. `adonis-app` is just a starter template. You can get rid of views just by removing the views directory and removing the `View provider` from the providers list.

Unfortunately I do not have any example of integrating nuxt, but in 4.0 I will make a more of a template based approach

**Comment by atinux** [comment]
That's a good news 👍 

We will work on an example with my brother @alexchopin for Adonis + Nuxt, I'll let you know when online.

**Comment by thetutlage** [comment]
👍

**Comment by alexchopin** [comment]
Hi, 

First of all you are doing a amazing work and thank you for that!

Second point, I started this repo called [Adonuxt](https://github.com/nuxt/adonuxt) for (Adonis + Nuxt) based on your adonis-app repo like you told us.

**Comment by thetutlage** [comment]
Boom. will try it out for sure.

I use Vue a lot and this repo will be goto tool for using both together. Thanks @alexchopin

**Comment by alexchopin** [comment]
Btw, do you have any idea why this error is throw when I'm trying to remove View module ?
```bash
Error: Cannot find module 'Adonis/Src/View'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at requireStack (/Users/Alexandre/Code/Local/Tests/adonuxt/node_modules/require-stack/src/index.js:44:12)
    at Object.Ioc.use (/Users/Alexandre/Code/Local/Tests/adonuxt/node_modules/adonis-fold/src/Ioc/index.js:382:14)
    at Object.closure (/Users/Alexandre/Code/Local/Tests/adonuxt/node_modules/adonis-framework/providers/ResponseProvider.js:15:24)
    at Object.Ioc._resolveProvider (/Users/Alexandre/Code/Local/Tests/adonuxt/node_modules/adonis-fold/src/Ioc/index.js:124:53)
    at Object.Ioc.use (/Users/Alexandre/Code/Local/Tests/adonuxt/node_modules/adonis-fold/src/Ioc/index.js:376:18)
    at Object.closure (/Users/Alexandre/Code/Local/Tests/adonuxt/node_modules/adonis-framework/providers/ServerProvider.js:16:28)
```
Thanks

**Comment by thetutlage** [comment]
Yes coz response provider has hard dependencies on the view provider. The best way is to register a fake view provider.

Same can be done here https://github.com/adonisjs/adonis-app/blob/develop/bootstrap/http.js#L23
or here https://github.com/adonisjs/adonis-app/blob/develop/app/Listeners/Http.js#L40

```js
Ioc.bind('Adonis/Src/View', function () {
   return {}
})
```

**Comment by alexchopin** [comment]
Ok, that's why. Thanks

**Comment by atinux** [comment]
It still think it could be really good to have a the possibility to have a really light version of Adonis @thetutlage 

With the ability of activating/disabling:
- the Static Provider/Middleware
- the View Provider
- Lucid
- etc.

This will allow AdonisJS to be used from micro-service to rich application.

**Comment by ajoslin103** [comment]
I would Very-Much like to have a lightweight option for Adonis -- I write all my front-end in Aurelia and Adonis seems like a very kindred spirit to Aurelia 

I want to use Adonis for authenticated & protected micro-services only

Personally I no longer believe in returning anything but data from the backend, leaving all presentation to the front-end, be it mobile or desktop or tablet

**Comment by thetutlage** [comment]
Which part due to think is heavy weight when writing the JSON api server?

**Comment by ajoslin103** [comment]
Honestly, I'm likely to be too new to Adonis to be of any real use to you yet.  I have been looking at server-side frameworks on and off since last fall in preparation to starting up server-side rewrites of several projects.  I like Adonis the most for what it offers and how it delivers it.  

I will be very interested in GraphQL this year as I am very much enamored with Neo4J from a recent project.  So I would say that being able to choose at project creation to include/ignore Views/Templating or Lucid would be a good start.  I am sure that later as I become more familiar with Adonis I'll have a better Idea.  

I'm just guessing here, but the easy workarounds of a fake view provider above would be better for me if there was a JSON view type that automatically converted my model to JSON and returned it as the response.

Can you share your hopes for when Adonis 4 will become usable?  If it's within a few months then I would much rather start with that than have to migrate later.  

I am very much looking forward to the combination of Aurelia & Adonis

**Comment by RomainLanz** [comment]
Instead of returning a view from your controller you can just return a model to create an API.

```javascript
* index (request, response) {
  const users = yield User.all()

  return response.ok(users)
}
```

**Comment by ajoslin103** [comment]
that's so clean and nice, thanks for the tip!

**Comment by thetutlage** [comment]
@ajoslin103 

Yes, the best part about Adonis is you can simply remove the providers you don't want from the `bootstrap/app.js` file.

So let's say if you decided to remove Lucid, you need to remove following

```
  'adonis-lucid/providers/DatabaseProvider',
  'adonis-lucid/providers/LucidProvider',
  'adonis-lucid/providers/FactoryProvider',
```

and 

```
  'adonis-lucid/providers/MigrationsProvider',
  'adonis-lucid/providers/SchemaProvider',
  'adonis-lucid/providers/SeederProvider',
```

Also I am interested in GraphQL too, haven't played much with it. 

Also as @RomainLanz said, returning plain json is as simple as return a Javascript object as the reponse.

```
response.send()
// or
response.json()
// or
response.all()
```

☝️ Same functionality, just different names

**Comment by ajoslin103** [comment]
sweet!  I am also attracted by it's approach to and support for security and authentication.  I am very much looking forward to seeing how much simpler things look when you can use async/await over generators!

**Comment by thetutlage** [comment]
Yup Adonis4.0 will use the approach of start lean and grow big, which means the initial project structure will be too small and as you want features, you can use ace commands to generate necessary directories

**Comment by ajoslin103** [comment]
looking forward to it!  thanks!

**Comment by thetutlage** [comment]
Also I tweeted recently on how small you can start with Adonis in near future https://twitter.com/adonisframework/status/855324876176932864

**Comment by RomainLanz** [comment]
Since there's the [`slim`](https://github.com/adonisjs/adonis-slim-app) blueprint now I think we can close this?

**Comment by thetutlage** [comment]
Yes, we can
