### ISSUE TITLE
Feature Request: [Lucid] Counting Related Models

### ISSUE THREAD

**Issue by helnokaly** [adonisjs/discussion#9]
It would be nice to add a way to eager load count of related models similar to this Laravel feature:

https://laravel.com/docs/5.3/eloquent-relationships#counting-related-models

### Examples:

```javascript
const Post = use('App/Model/Post')

const posts = yield Post
  .query()
  .withCount('comments')
  .fetch()

for (let post of posts) {
  console.log(post.comments_count) // integer
}
```

#### For multiple relations:

```javascript
const posts = yield Post
  .query()
  .withCount(['votes', 'comments'])
  .fetch()
````

#### With constraint:

```javascript
const posts = yield Post
  .query()
  .withCount('comments', builder => {
    builder.where('content', 'like', 'foo%')
  })
  .fetch()
```

**Comment by thetutlage** [comment]
Done a while back in Adonis 4.0, but since the issue was in wrong repo, never got a chance to reply here. http://dev.adonisjs.com/docs/4.0/relationships#_counts
